# Generated by Django 4.0.5 on 2022-06-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlot',
            name='owner_customer',
            field=models.ForeignKey(help_text='Владелец лота', on_delete=django.db.models.deletion.PROTECT, to='act.customer'),
        ),
        migrations.AlterField(
            model_name='customerlot',
            name='trade_winner',
            field=models.ForeignKey(blank=True, help_text='Победитель торга', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_lot', to='act.customer'),
        ),
    ]
