# Generated by Django 4.0.5 on 2022-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_alter_customerlot_owner_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс'),
        ),
    ]
